package persistanceClasses;

// Generated 04-oct-2015 21:23:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import persistanceClasses.Records;

/**
 * Datestopquantitys generated by hbm2java
 */
@Entity
@Table(name = "datestopquantitys", catalog = "c39melidatos")
public class Datestopquantitys implements java.io.Serializable {

	private Long idDateStopQuantitys;
	private Records records;
	private String date;
	private long stopQuantity;

	public Datestopquantitys() {
	}

	public Datestopquantitys(Records records, String date, long stopQuantity) {
		this.records = records;
		this.date = date;
		this.stopQuantity = stopQuantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDateStopQuantitys", unique = true, nullable = false)
	public Long getIdDateStopQuantitys() {
		return this.idDateStopQuantitys;
	}

	public void setIdDateStopQuantitys(Long idDateStopQuantitys) {
		this.idDateStopQuantitys = idDateStopQuantitys;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRecord", nullable = false)
	public Records getRecords() {
		return this.records;
	}

	public void setRecords(Records records) {
		this.records = records;
	}

	@Column(name = "date", nullable = false, length = 45)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "stopQuantity", nullable = false)
	public long getStopQuantity() {
		return this.stopQuantity;
	}

	public void setStopQuantity(long stopQuantity) {
		this.stopQuantity = stopQuantity;
	}

}
