package persistanceClasses;
// Generated 17-feb-2014 16:29:50 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Itemsquantitys generated by hbm2java
 */
@Entity
@Table(name = "itemsquantitys", catalog = "c39melidatos")
public class Itemsquantitys implements java.io.Serializable {

	private Long idItemsQuantitys;
	private Records records;
	private long offerQuantitys;
	private long soldQuantitys;

	public Itemsquantitys() {
	}

	public Itemsquantitys(Records records, long offerQuantitys,
			long soldQuantitys) {
		this.records = records;
		this.offerQuantitys = offerQuantitys;
		this.soldQuantitys = soldQuantitys;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idItemsQuantitys", unique = true, nullable = false)
	public Long getIdItemsQuantitys() {
		return this.idItemsQuantitys;
	}

	public void setIdItemsQuantitys(Long idItemsQuantitys) {
		this.idItemsQuantitys = idItemsQuantitys;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRecord", nullable = false)
	public Records getRecords() {
		return this.records;
	}

	public void setRecords(Records records) {
		this.records = records;
	}

	@Column(name = "offerQuantitys", nullable = false)
	public long getOfferQuantitys() {
		return this.offerQuantitys;
	}

	public void setOfferQuantitys(long offerQuantitys) {
		this.offerQuantitys = offerQuantitys;
	}

	@Column(name = "soldQuantitys", nullable = false)
	public long getSoldQuantitys() {
		return this.soldQuantitys;
	}

	public void setSoldQuantitys(long soldQuantitys) {
		this.soldQuantitys = soldQuantitys;
	}

}
