package persistanceClasses;
// Generated 17-feb-2014 16:29:50 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Itemprices generated by hbm2java
 */
@Entity
@Table(name = "itemprices", catalog = "c39melidatos")
public class Itemprices implements java.io.Serializable {

	private Long idItemsPrices;
	private Records records;
	private double avgPrices;
	private double maxPrices;
	private double minPrices;

	public Itemprices() {
	}

	public Itemprices(Records records, double avgPrices, double maxPrices,
			double minPrices) {
		this.records = records;
		this.avgPrices = avgPrices;
		this.maxPrices = maxPrices;
		this.minPrices = minPrices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idItemsPrices", unique = true, nullable = false)
	public Long getIdItemsPrices() {
		return this.idItemsPrices;
	}

	public void setIdItemsPrices(Long idItemsPrices) {
		this.idItemsPrices = idItemsPrices;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRecord", nullable = false)
	public Records getRecords() {
		return this.records;
	}

	public void setRecords(Records records) {
		this.records = records;
	}

	@Column(name = "avgPrices", nullable = false, precision = 22, scale = 0)
	public double getAvgPrices() {
		return this.avgPrices;
	}

	public void setAvgPrices(double avgPrices) {
		this.avgPrices = avgPrices;
	}

	@Column(name = "maxPrices", nullable = false, precision = 22, scale = 0)
	public double getMaxPrices() {
		return this.maxPrices;
	}

	public void setMaxPrices(double maxPrices) {
		this.maxPrices = maxPrices;
	}

	@Column(name = "minPrices", nullable = false, precision = 22, scale = 0)
	public double getMinPrices() {
		return this.minPrices;
	}

	public void setMinPrices(double minPrices) {
		this.minPrices = minPrices;
	}

}
