package persistanceClasses;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mercadopago generated by hbm2java
 */
@Entity
@Table(name = "mercadopago", catalog = "c39melidatos")
public class Mercadopago implements java.io.Serializable {

	private Long idMercadoPago;
	private Records records;
	private int acceptsMercadoPago;
	private int noMercadoPago;

	public Mercadopago() {
	}

	public Mercadopago(Records records, int acceptsMercadoPago,
			int noMercadoPago) {
		this.records = records;
		this.acceptsMercadoPago = acceptsMercadoPago;
		this.noMercadoPago = noMercadoPago;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMercadoPago", unique = true, nullable = false)
	public Long getIdMercadoPago() {
		return this.idMercadoPago;
	}

	public void setIdMercadoPago(Long idMercadoPago) {
		this.idMercadoPago = idMercadoPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRecord", nullable = false)
	public Records getRecords() {
		return this.records;
	}

	public void setRecords(Records records) {
		this.records = records;
	}

	@Column(name = "acceptsMercadoPago", nullable = false)
	public int getAcceptsMercadoPago() {
		return this.acceptsMercadoPago;
	}

	public void setAcceptsMercadoPago(int acceptsMercadoPago) {
		this.acceptsMercadoPago = acceptsMercadoPago;
	}

	@Column(name = "noMercadoPago", nullable = false)
	public int getNoMercadoPago() {
		return this.noMercadoPago;
	}

	public void setNoMercadoPago(int noMercadoPago) {
		this.noMercadoPago = noMercadoPago;
	}

}
