package persistanceClasses;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Publications generated by hbm2java
 */
@Entity
@Table(name = "publications", catalog = "c39melidatos")
public class Publications implements java.io.Serializable {

	private Long idPublication;
	private Records records;
	private String description;
	private String permalink;
	private double price;

	public Publications() {
	}

	public Publications(Records records, String description, String permalink,
			double price) {
		this.records = records;
		this.description = description;
		this.permalink = permalink;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPublication", unique = true, nullable = false)
	public Long getIdPublication() {
		return this.idPublication;
	}

	public void setIdPublication(Long idPublication) {
		this.idPublication = idPublication;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRecord", nullable = false)
	public Records getRecords() {
		return this.records;
	}

	public void setRecords(Records records) {
		this.records = records;
	}

	@Column(name = "description", nullable = false, length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "permalink", nullable = false, length = 200)
	public String getPermalink() {
		return this.permalink;
	}

	public void setPermalink(String permalink) {
		this.permalink = permalink;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
