package persistanceClasses;
// Generated 17-feb-2014 16:29:50 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "state", catalog = "c39melidatos")
public class State implements java.io.Serializable {

	private Integer idState;
	private String descState;
	private Set<Statesdata> statesdatas = new HashSet<Statesdata>(0);

	public State() {
	}

	public State(String descState) {
		this.descState = descState;
	}

	public State(String descState, Set<Statesdata> statesdatas) {
		this.descState = descState;
		this.statesdatas = statesdatas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idState", unique = true, nullable = false)
	public Integer getIdState() {
		return this.idState;
	}

	public void setIdState(Integer idState) {
		this.idState = idState;
	}

	@Column(name = "descState", nullable = false, length = 45)
	public String getDescState() {
		return this.descState;
	}

	public void setDescState(String descState) {
		this.descState = descState;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "state")
	public Set<Statesdata> getStatesdatas() {
		return this.statesdatas;
	}

	public void setStatesdatas(Set<Statesdata> statesdatas) {
		this.statesdatas = statesdatas;
	}

}
